[package]
name = "day07"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
indicatif = { workspace = true }
num-bigint = { workspace = true }
rayon = { workspace = true }
