[package]
name = "day24"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
indicatif = { workspace = true }
ndarray = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
tools = { workspace = true }
